language: node_js

node_js:
    - "stable"

cache:
  directories:
    - node_modules

script:
  - npm test

deploy:
  provider: lambda
  function_name: "cs3219-taskB-dev-api"
  region: "us-east-1"
  role: "arn:aws:iam::0123456789012:role/lambda_basic_execution"
  runtime: "nodejs4.3"
  handler_name: "handler"
