language: node_js

node_js:
    - "stable"

cache:
  directories:
    - node_modules

script:
  - npm test

deploy:
  provider: lambda
  function_name: "cs3219-taskB-dev-api"
  region: "us-east-2"
  role: "cs3219-taskB-dev-us-east-2-lambdaRole"
  runtime: "nodejs4.3"
  handler_name: "handler"
