service: cs3219-taskB

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  memorySize: 128
  timeout: 15

functions:
  app:
    handler: ./index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
