service: cs3219-taskB

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  memorySize: 128
  timeout: 15

functions:
  api:
    handler: lambda.handler #consider changing to index.handler since it is our entry point
    events:
      - http: ANY {proxy+}
      - http: ANY /
    environment:
      DB_SOURCE: 'atlas'
